#!/bin/bash

set -e

mkdir -p tmp
cd tmp

clang -S -emit-llvm ../*.cc -std=c++98
llvm-link -v *.ll -o ../container.bc

clang -c ../container.bc -o ../container.o

cd ..
rm -rf tmp

ln -srfv container.bc bitcode/
ln -srfv container.o obj/

ln -srf container.h include/
ln -srf trie.h include/
