#!/bin/bash

# output folders
rm -rf bitcode
mkdir -p bitcode

mkdir -p exec

mkdir -p obj

for i in $(ls -d src/*/)
do
	if [[ -e $i/build ]]
	then
		
		echo "┌────────────────────────────────"
		echo "│ Building in $i..."
		echo "└────────────────────────────────"
		
		PTH=$(pwd); cd $i
		
		./build
		cd $PTH
	fi
done

echo "┌────────────────────────────────"
echo "│ Generating libraries..."
echo "└────────────────────────────────"

llvm-link -v \
	src/pack/lgnpack.bc \
	src/container/cont.bc \
	src/rend/rend.bc \
	-o bitcode/lre.bc

echo "┌─────────────────┐"
echo "│ Build complete. │"
echo "└─────────────────┘"
