#!/bin/bash

# output folders
mkdir -p bitcode
mkdir -p exec

rm -r bitcode/*

for i in $(ls -d src/*/)
do
	if [[ -e $i/build ]]
	then
		
		echo "┌────────────────────────────────"
		echo "│ Building in $i..."
		echo "└────────────────────────────────"
		
		PTH=$(pwd); cd $i
		echo $PTH
		
		./build
		cd $PTH
	fi
done

echo "┌────────────────────────────────"
echo "│ Generating libraries..."
echo "└────────────────────────────────"

BITCODE="$(find bitcode -name '*.bc')"

llvm-link -v $BITCODE -o bitcode/lre.bc
rm -v $BITCODE

echo "┌─────────────────┐"
echo "│ Build complete. │"
echo "└─────────────────┘"
