#!/bin/bash

# output folders
rm -rf bitcode
mkdir -p bitcode

mkdir -p exec

mkdir -p obj

for i in $(ls -d src/*/)
do
	if [[ -e $i/build ]]
	then
		
		echo "▶▶▶ Building in $i"
		
		PTH=$(pwd); cd $i
		
		./build
		cd $PTH
	fi
done

echo "▶▶▶ Generating libraries..."

cd src
llvm-link -v "$(find -name '*.bc')" -o ../bitcode/lre.bc
cd ..

echo "▶▶▶ Build complete."
