#!/bin/bash

set -e

INCPATH=$(realpath ../../include/)

CLANGFLAGS="-std=c++98 -I$INCPATH -Wno-writable-strings"

mkdir -p tmp
cd tmp

clang -S -emit-llvm $CLANGFLAGS ../*.cc -std=c++98
llvm-link -v *.ll -o ../lgnpack.bc

cd ..
rm -rf tmp

clang -c lgnpack.bc -o lgnpack.o
clang main.cpp lgnpack.bc -I$INCPATH -o lgnpack  -lncurses

ln -srfv lgnpack ../../exec
