#!/bin/bash

set -e

CLANGFLAGS="-std=c++98 -I../../include -Wno-writable-strings"

# Build the standalone lgnpack binary
clang -lc++ -std=c++98 -g3 -static  \
		main.cpp *.cc -o lgnpack $CLANGFLAGS

ln -srvf lgnpack ../../exec

# Generate the lib
clang -S -emit-llvm $CLANGFLAGS *.cc 

FILES=$(find -name '*.ll')

llvm-link  -v -o pack.bc $FILES
rm $FILES
mv -v pack.bc ../../bin
