#!/bin/bash

if [[ -z "$(find -name '*.cc')" ]]
then
	exit 1
fi

mkdir -p tmp
cd tmp

clang -S -emit-llvm ../*.cc -std=c++98 -I$(realpath ../../include) -Wno-writable-strings
llvm-link -v *.ll -o ../rend.bc

cd ..
rm -rf tmp

clang -c rend.bc -o rend.o
