#!/bin/bash

set -e

clang -S -emit-llvm *.cc -std=c++98 \
	-I$(realpath ../../include) -Wno-writable-strings

FILES=$(find -name '*.ll')

llvm-link -v -o rend.bc $FILES
rm $FILES
mv -v rend.bc ../../bin
